---
- include_tasks:                '../tasks/commands.yml'
- include_tasks:                '../tasks/debconf.yml'
- include_tasks:                '../tasks/install_packages.yml'
- include_tasks:                '../tasks/template_files.yml'
- include_tasks:                '../tasks/symlinks.yml'
- include_tasks:                '../tasks/lines_in_files.yml'
- include_tasks:                '../tasks/enable_services.yml'
- include_tasks:                '../tasks/start_services.yml'
- include_tasks:                '../tasks/database_passwords.yml'
- include_tasks:                '../tasks/databases.yml'
- include_tasks:                '../tasks/shell_commands.yml'
  when:                         databases_result.changed
- include_tasks:                '../tasks/restart_services.yml'
  when:                         template_files_result.changed
                                or symlinks_result.changed
