---
- include:                      '../tasks/dependencies.yml'
- include:                      '../tasks/commands.yml'
- include:                      '../tasks/debconf.yml'
- include:                      '../tasks/install_packages.yml'
- include:                      '../tasks/template_files.yml'
- include:                      '../tasks/symlinks.yml'
- include:                      '../tasks/enable_services.yml'
- include:                      '../tasks/start_services.yml'
- include:                      '../tasks/database_passwords.yml'
- include:                      '../tasks/databases.yml'
- include:                      '../tasks/shell_commands.yml'
  when:                         databases_result.changed
- include:                      '../tasks/restart_services.yml'
  when:                         template_files_result.changed
                                or symlinks_result.changed
